# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    # Group ALL updates together to reduce builds
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"
    # Limit to 2 open PRs max
    open-pull-requests-limit: 2
    # Add reviewers (optional)
    reviewers:
      - "kraljic1"
    # Commit message preferences
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope" 