[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Development settings
[dev]
  port = 8889
  publish = "dist"
  targetPort = 5173
  command = "npm run dev"
  framework = "#auto"
  autoLaunch = true

# Handle client-side routing for React app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

# Redirect API calls to our serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Set proper MIME types for JavaScript modules
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:;"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

# Additional settings for form handling
[build.processing.html]
  pretty_urls = true

# Form notifications
[forms]
  [forms.checkout]
    name = "Order Submission Form"
    [forms.checkout.notifications]
      [forms.checkout.notifications.email]
        to = "vidk@codeandsail.com"
        subject = "New order submission from Smartblinds" 