[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Development settings
[dev]
  port = 8901
  command = "npm run dev"
  targetPort = 5173
  framework = "vite"
  autoLaunch = true

# Headers for development to allow all scripts and styles
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com https://m.stripe.network; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https: wss:; object-src 'none'; base-uri 'self';"

# Handle client-side routing for React app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

# Additional settings for form handling
[build.processing.html]
  pretty_urls = true

# Form notifications
[forms]
  [forms.checkout]
    name = "Order Submission Form"
    [forms.checkout.notifications]
      [forms.checkout.notifications.email]
        to = "vidk@codeandsail.com"
        subject = "New order submission from Smartblinds" 