[build]
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Development settings
[dev]
  port = 8901
  command = "npm run dev"
  targetPort = 5173
  framework = "vite"
  autoLaunch = true

# Headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(self \"https://js.stripe.com\" \"https://checkout.stripe.com\" \"https://api.stripe.com\"), usb=(), accelerometer=(), gyroscope=(), magnetometer=(), browsing-topics=(), run-ad-auction=(), join-ad-interest-group=(), private-state-token-redemption=(), private-state-token-issuance=(), private-aggregation=(), attribution-reporting=()"
    Cross-Origin-Embedder-Policy = "unsafe-none"
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    Cross-Origin-Resource-Policy = "cross-origin"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    # Comprehensive CSP to fix Stripe r.stripe.com blocking issues and allow Supabase
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com https://checkout.stripe.com https://m.stripe.com https://m.stripe.network; connect-src 'self' https://api.stripe.com https://js.stripe.com https://checkout.stripe.com https://q.stripe.com https://m.stripe.com https://merchant-ui-api.stripe.com https://r.stripe.com https://hooks.stripe.com https://m.stripe.network https://*.stripe.com wss://*.stripe.com https://*.supabase.co https://*.supabase.io wss://*.supabase.co wss://*.supabase.io; frame-src 'self' https://js.stripe.com https://checkout.stripe.com https://connect.stripe.com https://hooks.stripe.com; worker-src 'self' blob: https://m.stripe.network https://m.stripe.com; img-src 'self' data: https: blob: https://*.stripe.com https://*.stripecdn.com; style-src 'self' 'unsafe-inline' https://js.stripe.com https://checkout.stripe.com https://fonts.googleapis.com https://a.stripecdn.com; font-src 'self' https://a.stripecdn.com https://fonts.gstatic.com; form-action 'self'; base-uri 'self'; object-src 'none';"

# Handle client-side routing for React app - Updated after dark mode removal
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Additional settings for form handling
[build.processing.html]
  pretty_urls = true

# Form notifications
[forms]
  [forms.checkout]
    name = "Order Submission Form"
    [forms.checkout.notifications]
      [forms.checkout.notifications.email]
        to = "vidk@codeandsail.com"
        subject = "New order submission from Smartblinds"

# Force rebuild after dark mode removal - 2024-01-20 
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 