[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Development settings
[dev]
  port = 8888
  publish = "dist"
  targetPort = 5173
  command = "npm run dev"
  framework = "#auto"
  autoLaunch = true

# Handle client-side routing for React app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

# Redirect API calls to our serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Additional settings for form handling
[build.processing.html]
  pretty_urls = true

# Form notifications
[forms]
  [forms.checkout]
    name = "Order Submission Form"
    [forms.checkout.notifications]
      [forms.checkout.notifications.email]
        to = "vidk@codeandsail.com"
        subject = "New order submission from Smartblinds" 