[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Development settings
[dev]
  port = 8901
  command = "npm run dev"
  targetPort = 5173
  framework = "vite"
  autoLaunch = true

# Headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(self \"https://js.stripe.com\" \"https://checkout.stripe.com\" \"https://api.stripe.com\"), usb=(), accelerometer=(), gyroscope=(), magnetometer=()"
    Cross-Origin-Embedder-Policy = "unsafe-none"
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    Cross-Origin-Resource-Policy = "cross-origin"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"

# Handle client-side routing for React app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

# Additional settings for form handling
[build.processing.html]
  pretty_urls = true

# Form notifications
[forms]
  [forms.checkout]
    name = "Order Submission Form"
    [forms.checkout.notifications]
      [forms.checkout.notifications.email]
        to = "vidk@codeandsail.com"
        subject = "New order submission from Smartblinds" 