name: Automated Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    name: Update Dependencies
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check for security updates
      run: |
        echo "Checking for security updates..."
        npm audit fix --dry-run > security-updates.log 2>&1 || true
        if [ -s security-updates.log ]; then
          echo "Security updates available:"
          cat security-updates.log
        else
          echo "No security updates needed"
        fi
        
    - name: Apply security fixes
      run: |
        echo "Applying security fixes..."
        npm audit fix --force || true
        
    - name: Update patch versions
      run: |
        echo "Updating patch versions..."
        npm update
        
    - name: Check for major updates
      run: |
        echo "Checking for major updates..."
        npm outdated > major-updates.log 2>&1 || true
        if [ -s major-updates.log ]; then
          echo "Major updates available (manual review required):"
          cat major-updates.log
        fi
        
    - name: Run tests after updates
      run: |
        echo "Running security checks after updates..."
        npm run security-check || true
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: automated dependency security updates'
        title: 'Automated Dependency Security Updates'
        body: |
          ## Automated Dependency Updates
          
          This PR contains automated security updates and patch version bumps.
          
          ### Changes Made:
          - Applied security fixes via `npm audit fix`
          - Updated patch versions via `npm update`
          
          ### Security Status:
          - All known security vulnerabilities have been addressed
          - Dependencies have been updated to latest patch versions
          
          ### Review Required:
          Please review the changes and run tests before merging.
          
          Generated by automated dependency update workflow.
        branch: automated-dependency-updates
        delete-branch: true

  security-advisory-check:
    runs-on: ubuntu-latest
    name: Security Advisory Check
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check GitHub Security Advisories
      run: |
        echo "Checking GitHub Security Advisories..."
        npm audit --audit-level=low --json > security-advisories.json || true
        
        if [ -s security-advisories.json ]; then
          echo "Security advisories found!"
          # Parse and display critical information
          node -e "
            const fs = require('fs');
            try {
              const audit = JSON.parse(fs.readFileSync('security-advisories.json', 'utf8'));
              if (audit.vulnerabilities) {
                console.log('Vulnerabilities found:');
                Object.entries(audit.vulnerabilities).forEach(([pkg, vuln]) => {
                  console.log(\`- \${pkg}: \${vuln.severity} severity\`);
                  console.log(\`  Range: \${vuln.range}\`);
                  console.log(\`  Via: \${vuln.via.join(', ')}\`);
                });
              }
            } catch (e) {
              console.log('No vulnerabilities data found');
            }
          "
        else
          echo "No security advisories found"
        fi 